Invalidate sessions
wolox-training/rm-express-js pull request #16
Opened 2021-10-13 03:20 UTC by ricardoamoreno

## Summary

- /users/sessions/invalidate_all endpoint added
- sessionExpire field added to user model
- sessionExpireDate verification added on token
- invalidate_sessions tests added

## Known Issues

Issue in validateToken.js
Possible race condition: `req.user` might be reassigned. 
partial solution:  eslint-disable-next-line require-atomic-updates. 

## Trello Card

[Deshabilitar todas las sesiones](https://trello.com/c/vznJsZTT)

2021-10-13 13:02 UTC, martinremis requested changes
Well done! Just some comments

2021-10-13 13:02 UTC, martinremis commented on app/controllers/users.js
> +    res.status(200).send({ message: sessionClosedMessage });
This could better be a 204 without body

2021-10-13 13:02 UTC, martinremis commented on app/interactors/users.js
> +  return { userId: userSession[1][0].id };
Why do you return this? I think there is no need of return something here

2021-10-14 13:43 UTC, ricardoamoreno commented on app/controllers/users.js
> +    res.status(200).send({ message: sessionClosedMessage });
got it

2021-10-14 14:01 UTC, ricardoamoreno commented on app/interactors/users.js
> +  return { userId: userSession[1][0].id };
it's true, I deleted it

2021-10-19 13:12 UTC, martinremis approved these changes

2021-10-19 13:38 UTC, merged